name: act-linux_mac-release

runs:
  using: "composite"
  steps:
  
    - name: 'get-prep-location-upload-artifact'
      shell: bash
      run: |
        set -x
        #when checked, was node v0.10.48, will it run the upload-artifacts index.js, which wanted node12?
        yum -y install nodejs
        pwd
        git clone https://github.com/actions/upload-artifact ./gh.upload-artifact
        cd gh.upload-artifact
        git checkout tags/v2.2.4
        #sed "s/using: 'node12'/using: 'composite'/" action.yml
        #sed "s/main: 'dist\/index.js'/steps:/" action.yml
        #sed "$a\ \ \ \ - shell: bash" action.yml
        #sed "$a\ \ \ \ \ \ run: node dist/index.js" action.yml
        #~ cat > sed-upload-artifacts.patch <<EOF
          #~ s/using: 'node12'/using: 'composite'/
          #~ s/main: 'dist\/index.js'/steps:/
          #~ $a\ \ \ \ - shell: bash
          #~ $a\ \ \ \ \ \ run: node dist/index.js
        #~ EOF
        echo "s/using: 'node12'/using: 'composite'/" > sed-upload-artifact.patch
        echo "s/main: 'dist\/index.js'/steps:/" >> sed-upload-artifact.patch
        #echo "\$a\ \ \ \ - shell: bash" >> sed-upload-artifact.patch
        echo "\$a\\ \\ \\ \\ - shell: bash" >> sed-upload-artifact.patch
        #echo "\$a\ \ \ \ \ \ run: node dist/index.js" >> sed-upload-artifact.patch
        #echo "\$a\ \ \ \ \ \ run: node \$GITHUB_WORKSPACE/gh.upload-artifact/dist/index.js" >> sed-upload-artifact.patch
        echo "\$a\\ \\ \\ \\ \\ \\ run: node \$GITHUB_WORKSPACE/gh.upload-artifact/dist/index.js" >> sed-upload-artifact.patch
        cat sed-upload-artifact.patch
        hexdump -C sed-upload-artifact.patch
        sed -f ./sed-upload-artifact.patch action.yml > patched.action.yml
        rm action.yml
        mv patched.action.yml action.yml
        #~ cat > vi-upload-artifact.patch <<EOF
          #~ :%s/using: 'node12'/using: 'composite'/g
          #~ :%s/main: 'dist\/index.js'/steps:/g
          #~ G
          #~ A    - shell: bash
                #~ run: node dist/index.js
          #~ #how to insert ESCape to exit insert mode? <sigh>
        #~ EOF
        cat ./action.yml

    - name: 'Print env'
      run: |
        echo "'uname -s' is:"
        echo "uname: " $(uname)
        echo "uname -m: " $(uname -m)
        echo "uname -r:" $(uname -r)
        echo "uname -s: " $(uname -s)
        echo "uname -v: " $(uname -v)
        printenv
      shell: bash

    - name: 'Uninstall brew packages for curl (OSX only)'
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        set -e pipefail
        brew uninstall --ignore-dependencies libidn2 brotli rtmpdump

    - name: 'Remove sdks for testing (OSX only)'
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        set -e pipefail
        $SUDO rm -Rf /Library/Developer/CommandLineTools/SDKs/* # Remove SDKs without ARM support

    - name: 'Build libtiledb'
      #not availa le in (composite) action? continue-on-error: true
      shell: bash
      run: |
        # DELETEME work-around for https://github.com/microsoft/azure-pipelines-image-generation/issues/969
        #Needed for GA CI or not?... $SUDO chown root.root /

        # Azure sets "SYSTEM=build" for unknown reasonas, which breaks the OpenSSL configure script
        #   - openssl configure uses ENV{SYSTEM} if available:
        #     https://github.com/openssl/openssl/blob/6d745d740d37d680ff696486218b650512bbbbc6/config#L56
        #   - error description:
        #     https://developercommunity.visualstudio.com/content/problem/602584/openssl-build-error-when-using-pipelines.htm
        unset SYSTEM

        # azure bash does not treat intermediate failure as error
        # https://github.com/Microsoft/azure-pipelines-yaml/issues/135
        set -e pipefail

        git config --global user.name 'GACI Pipeline'
        git config --global user.email 'no-reply@tiledb.io'

        BUILD_REPOSITORY_LOCALPATH=$GITHUB_WORKSPACE
        # Set up arguments for bootstrap.sh
        BUILD_BINARIESDIRECTORY=${BUILD_BINARIESDIRECTORY:-$BUILD_REPOSITORY_LOCALPATH/dist}
        cmake_args="-DCMAKE_INSTALL_PREFIX=${BUILD_BINARIESDIRECTORY} -DTILEDB_TESTS=OFF -DTILEDB_INSTALL_LIBDIR=lib";
        mkdir -p ${BUILD_BINARIESDIRECTORY}

        # Enable TILEDB_STATIC by default
        [ "$TILEDB_STATIC" ] || TILEDB_STATIC=ON
        if [[ "$TILEDB_STATIC" == "ON" ]]; then
          cmake_args="${cmake_args} -DTILEDB_STATIC=ON";
        fi
        if [[ "$TILEDB_HDFS" == "ON" ]]; then
          cmake_args="${cmake_args} -DTILEDB_HDFS=ON";
        fi;
        if [[ "$TILEDB_S3" == "ON" ]]; then
          cmake_args="${cmake_args} -DTILEDB_S3=ON";
        fi;
        if [[ "$TILEDB_AZURE" == "ON" ]]; then
          cmake_args="${cmake_args} -DTILEDB_AZURE=ON";
        fi;
        if [[ "$TILEDB_GCS" == "ON" ]]; then
          cmake_args="${cmake_args} -DTILEDB_GCS=ON";
        fi;
        if [[ "$TILEDB_TOOLS" == "ON" ]]; then
          cmake_args="${cmake_args} -DTILEDB_TOOLS=ON";
        fi
        if [[ "$TILEDB_DEBUG" == "ON" ]]; then
          cmake_args="${cmake_args} -DCMAKE_BUILD_TYPE=Debug";
        fi
        if [[ "$TILEDB_CI_ASAN" == "ON" ]]; then
          # Add address sanitizer flag if necessary
          cmake_args="${cmake_args} -DSANITIZER=address";
        fi
        if [[ "$TILEDB_CI_TSAN" == "ON" ]]; then
          # Add thread sanitizer flag if necessary
          cmake_args="${cmake_args} -DSANITIZER=thread";
        fi
        if [[ "$TILEDB_SERIALIZATION" == "ON" ]]; then
          # Add serialization flag if necessary
          cmake_args="${cmake_args} -DTILEDB_SERIALIZATION=ON";
        fi
        if [[ "$TILEDB_FORCE_BUILD_DEPS" == "ON" ]]; then
          # Add superbuild flag
          cmake_args="${cmake_args} -DTILEDB_FORCE_ALL_DEPS=ON";
        fi
        if [[ "$TILEDB_WERROR" == "OFF" ]]; then
          # Add superbuild flag
          cmake_args="${cmake_args} -DTILEDB_WERROR=OFF";
        fi

        mkdir -p $BUILD_REPOSITORY_LOCALPATH/build
        cd $BUILD_REPOSITORY_LOCALPATH/build

        # Configure and build TileDB
        echo "Running cmake with '${cmake_args}'"
        cmake .. ${cmake_args}

        make -j4
        make -C tiledb install
        
        # get this into 'env' context since runners don't automatically place items
        # from env into context on startup!
        echo "GITHUB_SHA=$GITHUB_SHA" >> "$GITHUB_ENV"
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"
        echo "ARTIFACT_OS=$ARTIFACT_OS" >> "$GITHUB_ENV"
        echo "ARTIFACT_EXTRAS=$ARTIFACT_EXTRAS" >> "$GITHUB_ENV"
        
        set -x
        pwd
        #tar --exclude=build -zcf tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz $GITHUB_WORKSPACE
        pwd
        # sync in effort to avoid "tar: .: file changed as we read it" errors, guessing
        # based on logs seen, poss. due to files from install just above not yet having 
        # been completely written out with flushing happening during following 'tar' efforts.
        sync
        #sleep 10
        # move up a directory level so we are writing archive where tar won't fail reporting change while reading...
        cd $GITHUB_WORKSPACE/..
        pwd
        tar --exclude=build -vzcf tiledb-source-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz ./TileDB
        ls -l $GITHUB_WORKSPACE/..
        sync
        #sleep 10
        # move up a directory level so we are writing archive where tar won't fail reporting change while reading...
        cd $GITHUB_WORKSPACE/..
        pwd
        #tar -zcf tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz $GITHUB_WORKSPACE/build
        tar -vzcf tiledb-binary-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz ./TileDB/build
        ls -l $GITHUB_WORKSPACE/..
        sync
        TDB_SOURCE_ARCHIVE_PATH=`dirname $GITHUB_WORKSPACE/..`/tiledb-source-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz
        TDB_SOURCE_ARCHIVE_PATH2="$GITHUB_WORKSPACE/../tiledb-source-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz"
        echo "TDB_SOURCE_ARCHIVE_PATH=$TDB_SOURCE_ARCHIVE_PATH"
        #echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_SOURCE_ARCHIVE_PATH\"))\n" | /opt/rh/rh-python36/root/usr/bin/python
        echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_SOURCE_ARCHIVE_PATH\"))\n" | python
        echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_SOURCE_ARCHIVE_PATH2\"))\n" | python
        #would like to use 'realpath', but seems not present in manylinux, and failed finding package that has it, whereas
        #seems python functionality is present in all environs.
        #TDB_SOURCE_ARCHIVE_PATH=$(echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_SOURCE_ARCHIVE_PATH\"))\n" | /opt/rh/rh-python36/root/usr/bin/python)
        #TDB_SOURCE_ARCHIVE_PATH=$(echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_SOURCE_ARCHIVE_PATH\"))\n" | python)
        TDB_SOURCE_ARCHIVE_PATH=$(echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_SOURCE_ARCHIVE_PATH2\"))\n" | python)
        echo "TDB_SOURCE_ARCHIVE_PATH=$TDB_SOURCE_ARCHIVE_PATH"
        #TDB_SOURCE_ARCHIVE_PATH=`dirname $TDB_SOURCE_ARCHIVE_PATH`
        #echo "TDB_SOURCE_ARCHIVE_PATH=$TDB_SOURCE_ARCHIVE_PATH"
        echo "TDB_SOURCE_ARCHIVE_PATH=$TDB_SOURCE_ARCHIVE_PATH" >> "$GITHUB_ENV"

        TDB_BINARY_ARCHIVE_PATH=`dirname $GITHUB_WORKSPACE/..`/tiledb-binary-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz
        TDB_BINARY_ARCHIVE_PATH2="$GITHUB_WORKSPACE/../tiledb-binary-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz"
        echo "TDB_BINARY_ARCHIVE_PATH=$TDB_BINARY_ARCHIVE_PATH"
        #'realpath' not available everywhere, see comment above.
        #echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_BINARY_ARCHIVE_PATH\"))\n" | /opt/rh/rh-python36/root/usr/bin/python
        echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_BINARY_ARCHIVE_PATH\"))\n" | python
        echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_BINARY_ARCHIVE_PATH2\"))\n" | python
        #TDB_BINARY_ARCHIVE_PATH=$(echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_BINARY_ARCHIVE_PATH\"))\n" | /opt/rh/rh-python36/root/usr/bin/python)
        #TDB_BINARY_ARCHIVE_PATH=$(echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_BINARY_ARCHIVE_PATH\"))\n" | python)
        TDB_BINARY_ARCHIVE_PATH=$(echo -e "import sys\nimport os\nprint (os.path.realpath(\"$TDB_BINARY_ARCHIVE_PATH2\"))\n" | python)
        #TDB_BINARY_ARCHIVE_PATH=`dirname $TDB_BINARY_ARCHIVE_PATH`
        echo "TDB_BINARY_ARCHIVE_PATH=$TDB_BINARY_ARCHIVE_PATH"
        #echo "ARTIFACT_EXTRAS=$ARTIFACT_EXTRAS" >> "$GITHUB_ENV"
        echo "TDB_BINARY_ARCHIVE_PATH=$TDB_BINARY_ARCHIVE_PATH" >> "$GITHUB_ENV"
        
        ls -l $TDB_SOURCE_ARCHIVE_PATH
        ls -l $TDB_BINARY_ARCHIVE_PATH
        
        find / -name 'tiledb-*-linux-build-*.tar.gz' -exec ls -l {} \;

    - name: 'are variables in env context?'
      shell: bash
      run: |
        set -x
        echo "env.GITHUB_WORKSPACE is ${{ env.GITHUB_WORKSPACE }}"
        echo "env.GITHUB_SHA is ${{ env.GITHUB_SHA }}"
        echo "env.ARTIFACT_OS is ${{ env.ARTIFACT_OS }}"
        echo "env.ARTIFACT_EXTRAS is ${{ env.ARTIFACT_EXTRAS }}"
        echo "tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz"
        echo "TDB_SOURCE_ARCHIVE_PATH is $TDB_SOURCE_ARCHIVE_PATH"
        echo "TDB_BINARY_ARCHIVE_PATH is $TDB_BINARY_ARCHIVE_PATH"
        ls -l $TDB_SOURCE_ARCHIVE_PATH
        ls -l $TDB_BINARY_ARCHIVE_PATH
        echo "env.TDB_SOURCE_ARCHIVE_PATH is ${{ env.TDB_SOURCE_ARCHIVE_PATH }}"
        echo "env.TDB_BINARY_ARCHIVE_PATH is ${{ env.TDB_BINARY_ARCHIVE_PATH }}"
        sync
        #~ ls -l ${{ env.GITHUB_WORKSPACE }}/..
        #~ echo "${{ env.GITHUB_WORKSPACE }}/../tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz"
        #~ if [[ ! $(ls -l ${{ env.GITHUB_WORKSPACE }}/../tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz) ]]; then
          #~ echo failed ls -l ${{ env.GITHUB_WORKSPACE }}/../tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz
        #~ else
          #~ ls -l ${{ env.GITHUB_WORKSPACE }}/../tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz
        #~ fi
        #~ pwd
        find ${{ env.GITHUB_WORKSPACE }}/.. -name 'tiledb-*-linux-build-*.tar.gz' -exec ls -l {} \;
        printenv
        if [[ $(whoami) ]]; then
          echo $(whoami)
        else
          echo "couldn't figure out who I am"
        fi
        #no sudo... sudo ls -l
        if [[ $(ls -l /) ]]; then
          ls -l /
        else
          echo "unable to ls -l /"
        fi
        ls -l
        sync
        
    #~ - name: get-prep-location-upload-artifact
      #~ shell: bash
      #~ run: |
        #~ pwd
        #~ git clone https://github.com/actions/upload-artifact ./gh.upload-artifact
        #~ cd gh.upload-artifact
        #~ git checkout tags/v2.2.4
        #~ #sed "s/using: 'node12'/using: 'composite'/" action.yml
        #~ #sed "s/main: 'dist/index.js'/steps:/" action.yml
        #~ #sed "$a\ \ \ \ - shell: bash" action.yml
        #~ #sed "$a\ \ \ \ \ \ run: node dist/index.js" action.yml
        #~ cat > sed-upload-artifacts.patch <<EOF
          #~ s/using: 'node12'/using: 'composite'/
          #~ s/main: 'dist\/index.js'/steps:/
          #~ $a\ \ \ \ - shell: bash
          #~ $a\ \ \ \ \ \ run: node dist/index.js        
        #~ EOF
        #~ cat sed-upload-artifacts.patch
        #~ hexdump -C sed-upload-artifacts.patch
        #~ sed -f ./sed-upload-artifacts.patch action.yml > patched.action.yml
        #~ rm action.yml
        #~ mv patched.action.yml action.yml
        #~ cat > vi-upload-artifacts.patch <<EOF
          #~ :%s/using: 'node12'/using: 'composite'/g
          #~ :%s/main: 'dist\/index.js'/steps:/g
          #~ G
          #~ A    - shell: bash
                #~ run: node dist/index.js
          #~ #how to insert ESCape to exit insert mode? <sigh>
        #~ EOF
        #~ cat ./action.yml
        
    - name: 'ArchiveFiles@2A' # https://github.com/actions/upload-artifact#where-does-the-upload-go
      #if: ${{ failure() == true && startsWith(runner.name, 'macos-') == true }} # only run this job if the build step failed
      #uses: actions/upload-artifact@v2
      #uses: actions/upload-artifact@v1
      uses: ./gh.upload-artifact
      with:
        # @v1 does not recognize 'retention-days', 'if-no-files-found', path enhancments, prob more
        #retention-days: 10
        #name: "${{ runner.name }}.coredumps.${{ github.job }}.${{ github.run_number }}.${{github.run_id}}.${{github.run_attempt}}"
        #name: tiledb-$(ARTIFACT_OS)-build-dir-$(ARTIFACT_EXTRAS).tar.gz
        name: tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.${{github.job}}.tar.gz
        #if-no-files-found: warn # 'ignore/', 'warn' or 'error' are available, defaults to `warn`
        #${{ env.GITHUB_WORKSPACE }}/
        #!${{ env.GITHUB_WORKSPACE }}/build/
        #${{ env.GITHUB_WORKSPACE }}/../tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz
        #${{ env.TDB_SOURCE_ARCHIVE_PATH }}
        path: |
          CMakeLists.txt

    - name: Git Hash 7-digit
      shell: bash
      env: 
        sourceVersion: ${{ env.GITHUB_SHA }}
      run: |
        echo $sourceVersion
        commitHash=${sourceVersion:0:7}
        echo $commitHash
        #echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
        echo "::set-output name=commitHash::$commitHash" # TBD: make status check pass for this hack step
        
    - name: 'ArchiveFiles@2B' # https://github.com/actions/upload-artifact#where-does-the-upload-go
      # @v1 does not recognize 'retention-days', 'if-no-files-found', path enhancments, prob more
      #if: ${{ failure() == true && startsWith(runner.name, 'macos-') == true }} # only run this job if the build step failed
      #uses: actions/upload-artifact@v2
      #uses: actions/upload-artifact@v1
      uses: ./gh.upload-artifact
      with:
        #retention-days: 10
        #name: "${{ runner.name }}.coredumps.${{ github.job }}.${{ github.run_number }}.${{github.run_id}}.${{github.run_attempt}}"
        #name: tiledb-$(ARTIFACT_OS)-build-dir-$(ARTIFACT_EXTRAS).tar.gz
        name: tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.${{github.job}}.tar.gz
        #if-no-files-found: warn # 'ignore/', 'warn' or 'error' are available, defaults to `warn`
        #${{ env.GITHUB_WORKSPACE }}/build/
        #${{ env.GITHUB_WORKSPACE }}/../tiledb-${{ env.ARTIFACT_OS }}-build-dir-${{ env.ARTIFACT_EXTRAS }}.tar.gz
        #${{ env.TDB_BINARY_ARCHIVE_PATH }}
        path: |
          CMakeLists.txt
