name: build-macos-10.14-GCS
on:
  push:
    branches:
      - dev
      - release-*
      - refs/tags/*
  pull_request:
    branches:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string
env:
  BACKWARDS_COMPATIBILITY_ARRAYS: OFF
  TILEDB_GCS: OFF
  TILEDB_AZURE: ON
  TILEDB_SERIALIZATION: ON
  TILEDB_STATIC: OFF
  CXX: g++

jobs:
  build:
    runs-on: macos-10.15
    if: ${{ startsWith(github.ref , 'refs/tags') != true && startsWith(github.ref , 'build-') != true }}
    timeout-minutes: 90
    name: Build - macos-10.15 - AZURE
    steps:
      - uses: actions/checkout@v2
      - name: 'Print env'
        run: |
          echo "'uname -s' is:"
          echo "uname: " $(uname)
          echo "uname -m: " $(uname -m)
          echo "uname -r:" $(uname -r)
          echo "uname -s: " $(uname -s)
          echo "uname -v: " $(uname -v)
          printenv
        shell: bash

      # Need this for virtualenv and arrow tests if enabled
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: |
          set -e pipefail
          python -m pip install --upgrade pip virtualenv
          pip install pyarrow pybind11 numpy
        shell: bash

      - name: 'Build and test libtiledb'
        id: test
        run: |
          #Start azurite emulator 
          source scripts/install-azurite.sh;
          source scripts/run-azurite.sh;

          bootstrap_args="${bootstrap_args} --enable-azure";
          source $GITHUB_WORKSPACE/scripts/ci/build_libtiledb.sh

          make -j4 -C tiledb tiledb_unit

          # run directly the executable, cmake catches the segfault and blocks
          # the core dump
          ./tiledb/test/tiledb_unit -d yes

          #source $GITHUB_WORKSPACE/scripts/ci/build_benchmarks.sh

          # Kill the running Azurite server
          if [[ "$TILEDB_AZURE" == "ON" ]]; then
            kill -9 $AZURITE_PID
          fi

      - name: 'Test status check'
        run: |
          # tiledb_unit is configured to set a job-level variable TILEDB_CI_SUCCESS=1
          # following the test run. If this variable is not set, the build should fail.
          # see https://github.com/TileDB-Inc/TileDB/pull/1400 (5f0623f4d3)
          if [[ "${{ steps.test.outputs.TILEDB_CI_SUCCESS }}" -ne 1 ]]; then
            exit 1;
          fi
      #
      - name: "Print log files (failed build only)"
        run: |
          source $GITHUB_WORKSPACE/scripts/ci/print_logs.sh
        if: ${{ failure() }} # only run this job if the build step failed
