name: build-macos-AZURE
on:
  push:
    #~ branches:
      #~ - dev
      #~ - release-*
      #~ - refs/tags/*
  #~ pull_request:
    #~ branches:
      #~ - '*'  # must quote since "*" is a YAML reserved character; we want a string
env:
  BACKWARDS_COMPATIBILITY_ARRAYS: OFF
  TILEDB_GCS: OFF
  TILEDB_AZURE: ON
  TILEDB_SERIALIZATION: ON
  TILEDB_STATIC: OFF
  CXX: clang++

jobs:
  build:
    runs-on: macos-10.15
    if: ${{ startsWith(github.ref , 'refs/tags') != true && startsWith(github.ref , 'build-') != true }}
    timeout-minutes: 90
    name: Build - macos-10.15 - AZURE
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/linux_mac

  #~ build_linux_asan:
    #~ runs-on: ubuntu-20.04
    #~ if: ${{ startsWith(github.ref , 'refs/tags') != true && startsWith(github.ref , 'build-') != true }}
    #~ timeout-minutes: 90
    #~ name: Build - linux_asan
    #~ env:
      #~ #BACKWARDS_COMPATIBILITY_ARRAYS: OFF
      #~ #TILEDB_GCS: OFF
      #~ #TILEDB_AZURE: ON
      #~ TILEDB_CI_ASAN: ON
      #~ TILEDB_SERIALIZATION: ON
      #~ #TILEDB_STATIC: OFF
      #~ CXX: g++
      #~ CC: gcc
    #~ steps:
      #~ - uses: actions/checkout@v2

      #~ - uses: ./.github/actions/linux_mac
