name: build-ubuntu-20.04-AZURE
on:
  push:
    #~ branches:
      #~ - dev
      #~ - release-*
      #~ - refs/tags/*
  #~ pull_request:
    #~ branches:
      #~ - '*'  # must quote since "*" is a YAML reserved character; we want a string

env:
  BACKWARDS_COMPATIBILITY_ARRAYS: OFF
  TILEDB_AZURE: ON
  TILEDB_STATIC: OFF
  TILEDB_ARROW_TESTS: ON
  #CXX: g++
  MANYLINUX_IMAGE: 'quay.io/pypa/manylinux2010_x86_64:2021-11-07-28723f3'

jobs:
  build:
    runs-on: ${{ matrix.os }} #ubuntu-20.04
    strategy:
      matrix:
        #os: [ubuntu-20.04, macos-10.15]
        #os: [macos-10.15]
        os:
          #~ - ubuntu-20.04
            #~ cxx: g++
            #~ tiledb_serialization: OFF
            #~ artifact_os: macOS_azure
            #~ tiledb_try_png_ingestion: ON
          - macos-10.15
        include:
          - os: 'macos-10.15'
            cxx: clang++
            tiledb_serialization: ON
            artifact_os: macOS_azure
            try_png_ingestion: OFF
    if: ${{ startsWith(github.ref , 'refs/tags') != true && startsWith(github.ref , 'build-') != true }}
    timeout-minutes: 90
    #name: Build - ubuntu-20.04 - AZURE
    name: Build - macos-10.15 - AZURE
    env:
      TILEDB_HOME: ${{ github.workspace }}
      TILEDB_GA_IMAGE_NAME: ${{ matrix.os }}
      CXX: ${{ matrix.cxx }}
      TILEDB_SERIALIZATION: ${{ matrix.tiledb_serialization }}
      ARTIFACT_OS: ${{ matrix.artifact_os }}
      TILEDB_TRY_PNG_INGESTION: ${{ matrix.try_png_ingestion }}
    steps:
    
      - name: 'force core attempt'
        run: |
          ls -la /cores
          # enable core dumps
          ulimit -c               # should output 0 if disabled
          ulimit -c unlimited     # Enable core dumps to be captured (must be in same run block)
          ulimit -c               # should output 'unlimited' now
          # try to force a core dump to test core dump artifacts gathering
          echo "hello, about to sleep in sub-bash..."
          #sh -c "sleep 5" &
          # appears macos kill is different than some others...
          printenv
          echo "BASHPID $BASHPID"
          echo "PPID $PPID"
          #bash -c "echo $BASHPID, $$; ulimit -c unlimited; ulimit -c; ps -A; sleep 20; kill -n 6 $BASHPID" &
          #bash -c 'echo $BASHPID, $$; ulimit -c unlimited; ulimit -c; ps -A; sleep 20; kill -n 6 $$' &
          #bash -c 'echo $BASHPID, $PPID, $$; ulimit -c unlimited; ulimit -c; ps -A; sleep 20; kill -n 6 $PPID' &
          #bash -c 'echo $BASHPID, $PPID, $$; ulimit -c unlimited; ulimit -c; ps -A; sleep 20; kill -n 4 $PPID' &
          lastpid=$!
          echo sub-bash sleep invoked...
          #kill --help
          echo "sub-bash lastpid is $lastpid"
          which ps
          which kill
          #ps -A
          #ls -la /cores
          #kill -QUIT $lastpid
          #kill -ABRT $lastpid
          #kill -SEGV $lastpid
          #kill -l
          #kill --list
          #kill -SIGABRT $lastpid 
          #kill -s SIGABRT $lastpid 
          #kill -6 $lastpid # SIGABRT
          #kill -11 $lastpid # SIGSEGV
          #kill -4 $lastpid # SIGILL
          #kill -SIGSEGV $lastpid
          #ls -la /cores
          echo "waiting on $lastpid..."
          #wait $lastpid
          #kill -L
          #TBD -e valid in macos environ?
          which python
          which python3
          #echo -e "print('about to abort!') \nimport os \nos.abort()" | python
          ls -la /cores
          echo "about to exit with 137..."
          #exit 137
        
      - uses: actions/checkout@v2

      #~ - name: 'prep env'
        #~ run: |
          #~ if [[ $TILEDB_GA_IMAGE_NAME == 'ubuntu-20.04' ]] ; then
            #~ echo "CXX=g++" >> "$GITHUB_ENV"
          #~ fi
          #~ if [[ $TILEDB_GA_IMAGE_NAME == 'macos-10.15' ]] ; then
            #~ echo "CXX=clang++" >> "$GITHUB_ENV"
            #~ echo "TILEDB_SERIALIZATION=ON" >> "$GITHUB_ENV"
            #~ echo "ARTIFACT_OS=macOS_azure" >> "$GITHUB_ENV"
          #~ fi
        #~ shell: bash
        
      - name: 'Print env'
        run: |
          echo "'uname -s' is:"
          echo "uname: " $(uname)
          echo "uname -m: " $(uname -m)
          echo "uname -r:" $(uname -r)
          echo "uname -s: " $(uname -s)
          echo "uname -v: " $(uname -v)
          printenv
        shell: bash

      # Need this for virtualenv and arrow tests if enabled
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: |
          set -e pipefail
          python -m pip install --upgrade pip virtualenv
          pip install pyarrow pybind11 numpy
        shell: bash

      - name: 'Build and test libtiledb'
        id: test
        run: |
          # Azure sets "SYSTEM=build" for unknown reasonas, which breaks the OpenSSL configure script
          #   - openssl configure uses ENV{SYSTEM} if available:
          #     https://github.com/openssl/openssl/blob/6d745d740d37d680ff696486218b650512bbbbc6/config#L56
          #   - error description:
          #     https://developercommunity.visualstudio.com/content/problem/602584/openssl-build-error-when-using-pipelines.htm
          unset SYSTEM

          # azure run does not treat intermediate failure as error
          # https://github.com/Microsoft/azure-pipelines-yaml/issues/135
          set -e pipefail

          git config --global user.name 'Azure Pipeline'
          git config --global user.email 'no-reply@tiledb.io'

          # Start Azurite - Azure is enabled
          source scripts/install-azurite.sh;
          source scripts/run-azurite.sh;

          bootstrap_args="${bootstrap_args} --enable-azure";
          source $GITHUB_WORKSPACE/scripts/ci/build_libtiledb.sh
          
          # Bypass Catch2 Framework stdout interception with awk on test output
          # make check | awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'
          ./tiledb/test/tiledb_unit -d yes | awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'

          # Kill the running Azurite server
          kill -n 9 $AZURITE_PID

          # - bash: |
          pushd $GITHUB_WORKSPACE/examples/cmake_project
          mkdir build && cd build
          cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/dist .. && make
          ./ExampleExe

          popd
          
          if [[ $TILEDB_TRY_PNG_INGESTION == "ON" ]]; then
            # Build and run the PNG ingestion example.
            # libpng (example dependency)
            sudo apt-get install libpng-dev

            pushd $GITHUB_WORKSPACE/examples/png_ingestion;
            mkdir build && cd build;
            cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/dist .. && make;
            ./tiledb_png $GITHUB_WORKSPACE/doc/source/figures/Scarlet-Macaw-small.png /tmp/pngarray output.png;
            popd;
          fi

          source $GITHUB_WORKSPACE/scripts/ci/build_benchmarks.sh
          
          ulimit -c               # should output 0 if disabled
          ulimit -c unlimited     # Enable core dumps to be captured (must be in same run block)
          ulimit -c               # should output 'unlimited' now
          #echo -e "import resource as res\nres.setrlimit(resource.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIMIT_INFINITY))\nprint(res.getrlimit(4))\nprint('about to abort!') \nimport os \nos.abort()" | python
          echo -e "import resource as res\nprint(res.getrlimit(res.RLIMIT_CORE))\nres.setrlimit(res.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIM_INFINITY))\nprint(res.getrlimit(res.RLIMIT_CORE))\nimport os \nos.abort()" | python3
          
      - name: 'Save cores dump stacks if any'
        if: ${{ failure() == true && startsWith(matrix.os, 'macos-') == true }} # only run this job if the build step failed
        run: |
          ls -la /cores
          mkdir $TILEDB_HOME/build/core
          #mv /cores/core.* $TILEDB_HOME/build/core/core.1
          ls -la $TILEDB_HOME/build/core
          #lldb -c $TILEDB_HOME/build/core/core.1 --batch -o 'bt all' -o 'quit'
          for f in $(find $TILEDB_HOME/build/core);
            do
              lldb -c $f --batch -o 'bt all' -o 'quit'
            done;

      - name: 'upload any core artifacts' # https://github.com/actions/upload-artifact#where-does-the-upload-go
        if: ${{ failure() == true && startsWith(matrix.os, 'macos-') == true }} # only run this job if the build step failed
        uses: actions/upload-artifact@v2
        with:
          retention-days: 10
          #name: ${{ github.id }} -cores
          name: coredumps ${{ env.GITHUB_RUN_NUMBER }} 
          if-no-files-found: warn # 'ignore', 'warn' or 'error' are available, defaults to `warn` 
          path: |
            !${{ github.workspace }}/build/core/

      - name: 'Test status check'
        run: |
          # tiledb_unit is configured to set a job-level variable TILEDB_CI_SUCCESS=1
          # following the test run. If this variable is not set, the build should fail.
          # see https://github.com/TileDB-Inc/TileDB/pull/1400 (5f0623f4d3)
          if [[ "${{ steps.test.outputs.TILEDB_CI_SUCCESS }}" -ne 1 ]]; then
            exit 1;
          fi

      - name: "Print log files (failed build only)"
        run: |
          source $GITHUB_WORKSPACE/scripts/ci/print_logs.sh
        if: ${{ failure() }} # only run this job if the build step failed

  manylinux-container-job:
    runs-on: ${{ matrix.os }}
    if: false
    strategy:
      matrix:
        #os: [ubuntu-20.04, macos-10.15]
        #os: [macos-10.15]
        os:
          #~ - ubuntu-20.04
            #~ cxx: g++
            #~ tiledb_serialization: OFF
            #~ artifact_os: macOS_azure
            #~ tiledb_try_png_ingestion: ON
          - macos-10.15
        include:
          - os: 'macos-10.15'
            image: 'quay.io/pypa/manylinux2010_x86_64:2021-11-07-28723f3'
    container: ${{ matrix.os.image }} # TBD: Is this/that right location for image?
    #services:
    #  manylinux:
    #    image: ${{ matrix.os.image }} # TBD: Is this/that right location for image?
    steps:
      - name: 'something to fill til real work coded'
        run: echo running in container? # to be replaced with something more substantial (azure-linux_mac.yml GA quiv?)
