name: linux_mac-release

on:
  push:
    branches:
      - release-*
      - dlh/ch10040-azr-osx-lnxto-ga
    
env:
  SUDO: 'sudo'
    
jobs:
  build-release-macos:
    runs-on: ${{ matrix.os }}
    env:
      TILEDB_S3: ON
      TILEDB_AZURE: ON
      TILEDB_GCS: ON
      TILEDB_HDFS: ON
      TILEDB_STATIC: OFF
      TILEDB_SERIALIZATION: ON
      TILEDB_FORCE_BUILD_DEPS: ON
      MACOSX_DEPLOYMENT_TARGET: 10.14
      SUDO: 'sudo'
    strategy:
      matrix:
        #https://github.community/t/create-matrix-with-multiple-os-and-env-for-each-one/16895/5
        include:
          - os: macos-10.15
            TILEDB_AZURE: ON
            TILEDB_SERIALIZATION: ON
            CXX: clang++
            ARTIFACT_OS: macOS_azure
          - os: macos-10.15
            CXX: clang++
            ARTIFACT_OS: 'macos'
            ARTIFACT_ARCH: 'arm64'
            TILEDB_GCS: OFF
            TILEDB_WERROR: OFF
            CMAKE_OSX_ARCHITECTURES: "arm64"
            MACOSX_DEPLOYMENT_TARGET: 11
    steps:
      - uses: actions/checkout@v1

      - uses: ./.github/actions/linux_mac-release

  configure-for-manylinux-container:
    runs-on: ubuntu-20.04
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
          
  build-release-manylinux:
    needs: configure-for-manylinux-container
    runs-on: ubuntu-20.04
    env:
      CXX: g++
      CFLAGS: "-lrt"
      CXXFLAGS: "-lrt"
      ARTIFACT_OS: 'linux'
      ARTIFACT_ARCH: 'x86_64'
      SUDO: ''
    container: #${{ matrix.os.image }} # TBD: Is this/that right location for image?
      image: 'quay.io/pypa/manylinux2010_x86_64:2021-11-07-28723f3'      
      #options: "--entrypoint /bin/bash"
      options: --user ${{ needs.configure-for-manylinux-container.outputs.uid_gid }}
    steps:
      #~ - name: 'are we in container?'
        #~ shell: bash
        #~ run: |
          #~ if [[ $(ls -l /etc/system-release) ]]; then
            #~ echo "found system-release"
            #~ cat /etc/system-release
          #~ else
            #~ echo "did not find system-release"
          #~ fi
          #~ exit 45

      - uses: actions/checkout@v1

      - uses: ./.github/actions/linux_mac-release

